[package]
name = "ha-setup"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cassandra-cpp = "3.0.2"
tokio = { version = "1.38.0", features = ["macros", "rt-multi-thread"] }
